// Mock product data with real images from reliable sources
export const products = [
  {
    id: '1',
    name: 'Wireless Bluetooth Headphones',
    price: 159.99,
    originalPrice: 199.99,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&h=500&fit=crop',
    category: 'electronics',
    rating: 4.5,
    reviews: 128,
    description: 'Premium wireless headphones with noise cancellation and 30-hour battery life.',
    inStock: true,
    featured: true,
    tags: ['wireless', 'audio', 'bluetooth']
  },
  {
    id: '2',
    name: 'Smart Fitness Watch',
    price: 249.99,
    originalPrice: 299.99,
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&h=500&fit=crop',
    category: 'electronics',
    rating: 4.7,
    reviews: 89,
    description: 'Advanced fitness tracking with heart rate monitor and GPS.',
    inStock: true,
    featured: true,
    tags: ['fitness', 'smartwatch', 'health']
  },
  {
    id: '3',
    name: 'Organic Cotton T-Shirt',
    price: 29.99,
    originalPrice: 39.99,
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&h=500&fit=crop',
    category: 'fashion',
    rating: 4.3,
    reviews: 256,
    description: 'Comfortable organic cotton t-shirt in multiple colors.',
    inStock: true,
    featured: false,
    tags: ['organic', 'cotton', 'casual']
  },
  {
    id: '4',
    name: 'Leather Crossbody Bag',
    price: 89.99,
    originalPrice: 119.99,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500&h=500&fit=crop',
    category: 'fashion',
    rating: 4.6,
    reviews: 45,
    description: 'Handcrafted leather crossbody bag perfect for everyday use.',
    inStock: true,
    featured: true,
    tags: ['leather', 'handbag', 'accessories']
  },
  {
    id: '5',
    name: 'Gaming Mechanical Keyboard',
    price: 129.99,
    originalPrice: 159.99,
    image: 'https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=500&h=500&fit=crop',
    category: 'electronics',
    rating: 4.8,
    reviews: 312,
    description: 'RGB backlit mechanical keyboard with tactile switches.',
    inStock: true,
    featured: false,
    tags: ['gaming', 'keyboard', 'RGB']
  },
  {
    id: '6',
    name: 'Skincare Set',
    price: 79.99,
    originalPrice: 99.99,
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=500&h=500&fit=crop',
    category: 'beauty',
    rating: 4.4,
    reviews: 178,
    description: 'Complete skincare routine with natural ingredients.',
    inStock: true,
    featured: true,
    tags: ['skincare', 'natural', 'beauty']
  },
  {
    id: '7',
    name: 'Yoga Mat Premium',
    price: 49.99,
    originalPrice: 69.99,
    image: 'https://images.unsplash.com/photo-1506629905607-676bb2f3f0e1?w=500&h=500&fit=crop',
    category: 'sports',
    rating: 4.5,
    reviews: 89,
    description: 'Non-slip yoga mat made from eco-friendly materials.',
    inStock: true,
    featured: false,
    tags: ['yoga', 'fitness', 'eco-friendly']
  },
  {
    id: '8',
    name: 'Stainless Steel Water Bottle',
    price: 24.99,
    originalPrice: 34.99,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500&h=500&fit=crop',
    category: 'lifestyle',
    rating: 4.6,
    reviews: 234,
    description: 'Double-walled insulated water bottle keeps drinks cold for 24h.',
    inStock: true,
    featured: false,
    tags: ['water bottle', 'insulated', 'eco']
  },
  {
    id: '9',
    name: 'Professional Camera Lens',
    price: 699.99,
    originalPrice: 899.99,
    image: 'https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=500&h=500&fit=crop',
    category: 'electronics',
    rating: 4.9,
    reviews: 67,
    description: 'High-quality 50mm f/1.4 lens for professional photography.',
    inStock: true,
    featured: true,
    tags: ['camera', 'lens', 'photography']
  },
  {
    id: '10',
    name: 'Minimalist Wall Clock',
    price: 39.99,
    originalPrice: 49.99,
    image: 'https://images.unsplash.com/photo-1563906267088-b029e7101114?w=500&h=500&fit=crop',
    category: 'home',
    rating: 4.2,
    reviews: 156,
    description: 'Modern minimalist wall clock perfect for any room.',
    inStock: true,
    featured: false,
    tags: ['home decor', 'clock', 'minimalist']
  },
  {
    id: '11',
    name: 'Wireless Charging Station',
    price: 59.99,
    originalPrice: 79.99,
    image: 'https://images.unsplash.com/photo-1609081219090-a6d81d3085bf?w=500&h=500&fit=crop',
    category: 'electronics',
    rating: 4.4,
    reviews: 98,
    description: 'Fast wireless charging station for multiple devices.',
    inStock: true,
    featured: false,
    tags: ['wireless charging', 'tech', 'accessories']
  },
  {
    id: '12',
    name: 'Artisan Coffee Beans',
    price: 18.99,
    originalPrice: 24.99,
    image: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=500&h=500&fit=crop',
    category: 'food',
    rating: 4.7,
    reviews: 445,
    description: 'Single-origin artisan coffee beans, medium roast.',
    inStock: true,
    featured: true,
    tags: ['coffee', 'organic', 'artisan']
  }
]

export const categories = [
  { id: 'all', name: 'All Products', count: products.length },
  { id: 'electronics', name: 'Electronics', count: products.filter(p => p.category === 'electronics').length },
  { id: 'fashion', name: 'Fashion', count: products.filter(p => p.category === 'fashion').length },
  { id: 'beauty', name: 'Beauty', count: products.filter(p => p.category === 'beauty').length },
  { id: 'sports', name: 'Sports', count: products.filter(p => p.category === 'sports').length },
  { id: 'lifestyle', name: 'Lifestyle', count: products.filter(p => p.category === 'lifestyle').length },
  { id: 'home', name: 'Home & Garden', count: products.filter(p => p.category === 'home').length },
  { id: 'food', name: 'Food & Drinks', count: products.filter(p => p.category === 'food').length },
]
